export const links = [
  { from: '1', to: '2' },
  { from: '1', to: '3' },
  { from: '1', to: '4' },
  { from: '1', to: '5' },
  { from: '2', to: '6' },
  { from: '3', to: '6' },
  { from: '4', to: '7' },
  { from: '5', to: '8' },
  { from: '1', to: '9' },
  { from: '9', to: '10' },
]
export const nodes = [
  {
    id: '1',
    title: 'VPC',
    type: 'vpc',
    icon: 'vpc-1.svg',
    children: [
      {
        id: '2',
        type: 'nats',
        title: 'NAT网关',
        num: 0,
        position: 'left',
        icon: 'nat.svg',
        instances: [],
        children: [{ id: '6', title: 'INTERNET', position: 'left', icon: 'internet.svg' }],
      },
      { id: '3', title: '负载均衡', type: 'slbs', num: 0, position: 'left', icon: 'slb.svg', instances: [] },
      {
        id: '4',
        title: '对等连接',
        type: 'peers',
        num: 0,
        position: 'left',
        icon: 'peers.svg',
        instances: [],
        children: [{ id: '7', title: '对端VPC', position: 'left', icon: 'vpc.svg' }],
      },
      {
        id: '5',
        title: '云专线',
        type: 'edcs',
        num: 0,
        position: 'left',
        icon: 'edcs.svg',
        instances: [],
        children: [{ id: '8', title: '对端位置', position: 'left', icon: 'postion.svg' }],
      },
      {
        title: 'subnet-escl',
        id: '9',
        cidr: '10.0.0.0/8',
        shape: 'line',
        typeName: '子网',
        children: [
          {
            icon: 'evm.svg',
            typeId: 'evm',
            num: 1,
            title: '虚拟机',
            instances: [
              {
                ip: '10.0.0.2',
                resourceTypeId: 'evm',
                name: 'evm-4xy5zejsbzeo',
                resourceHref: '#/instance/evm/detail?tab=info&id=650609962384551936&workspaceId=10012660',
                nodeIp: '192.168.212.14',
                id: '650609962384551936',
                state: 'online',
                spec: 's6.2xlarge.4 | 8vCPUs | 32GiB',
                resourceTypeName: '虚拟机',
              },
            ],
            type: 'evm',
            position: 'bottom',
            borderRadius: '0',
            id: '10',
          },
        ],
      },
    ],
  },
]
