apiVersion: v1
kind: Service
metadata:
  name: scaffold
  labels:
    app: scaffold
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: scaffold
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaffold
  labels:
    app: scaffold
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scaffold
  template:
    metadata:
      labels:
        app: scaffold
    spec:
      containers:
      - image: {imagename}
        imagePullPolicy: IfNotPresent
        name: scaffold
        ports:
        volumeMounts:
          - name: config-volume
            mountPath: /etc/nginx/conf.d
      volumes:
        - name: config-volume
          configMap:
            name: scaffold
      hostAliases:
      - ip: "36.111.140.220"
        hostnames:
          - "iam-test.ctcdn.cn"
          - "portal-iam-test.ctyuncdn.cn"
          - "portal-iam-online.ctyuncdn.cn"
          - "eapd.develop.ctcdn.cn"
      - ip: "219.147.102.17"
        hostnames:
          - "www.ctyun.cn"
