apiVersion: v1
kind: Service
metadata:
  name: scaffold
  labels:
    app: scaffold
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8047
  selector:
    app: scaffold
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaffold
  labels:
    app: scaffold
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scaffold
  template:
    metadata:
      labels:
        app: scaffold
    spec:
      containers:
      - image: {imagename}
        imagePullPolicy: IfNotPresent
        name: scaffold
        ports:
        - containerPort: 8047
