apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: {{DEPLOYMENT_NAME}}
  name: {{DEPLOYMENT_NAME}}
  namespace: {{NAMESPACE}}
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: {{DEPLOYMENT_NAME}}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: {{DEPLOYMENT_NAME}}
    spec:
      imagePullSecrets:
        - name: harboreg
      dnsConfig:
        options:
          - name: single-request-reopen
      containers:
        - image: {{imageUrl}}
          imagePullPolicy: IfNotPresent
          name: {{DEPLOYMENT_NAME}}
      hostAliases:
        - ip: "36.111.140.220"
          hostnames:
            - "iam-test.ctcdn.cn"
            - "portal-iam-test.ctyuncdn.cn"
            - "portal-iam-online.ctyuncdn.cn"
            - "eapd.develop.ctcdn.cn"
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
