export interface IScssVariablesRevised {
  colorMaster: string
  colorMasterHover: string
  colorMasterActive: string
  colorMasterDisabled: string
  colorMasterBg: string
  colorMasterBgLight: string
  colorMasterBgLight2: string
  colorMaster1: string
  colorMaster2: string
  colorMaster3: string
  colorMaster4: string
  colorMaster5: string
  colorMaster6: string
  colorMaster7: string
  colorCt: string
  colorCtHover: string
  colorCtActive: string
  colorCtDisabled: string
  colorSp1: string
  colorSp2: string
  colorSp3: string
  colorInfo: string
  colorInfoHover: string
  colorInfoActive: string
  colorInfoDisabled: string
  colorInfoBg: string
  colorSuccess: string
  colorSuccessHover: string
  colorSuccessActive: string
  colorSuccessDisabled: string
  colorSuccessBg: string
  colorWarning: string
  colorWarningHover: string
  colorWarningActive: string
  colorWarningDisabled: string
  colorWarningBg: string
  colorDanger: string
  colorDangerHover: string
  colorDangerActive: string
  colorDangerDisabled: string
  colorDangerBg: string
  colorFatal: string
  colorFatalHover: string
  colorFatalActive: string
  colorFatalDisabled: string
  colorFatalBg: string
  colorStatusMaster: string
  colorStatusMaster1: string
  colorStatusDanger: string
  colorStatusDanger1: string
  colorStatusDanger2: string
  colorStatusDanger3: string
  colorStatusInfo: string
  colorStatusInfo1: string
  colorStatusSuccess: string
  colorStatusSuccess1: string
  colorStatusWarning: string
  colorStatusWarning1: string
  colorNeutral1: string
  colorNeutral2: string
  colorNeutral3: string
  colorNeutral4: string
  colorNeutral5: string
  colorNeutral6: string
  colorNeutral7: string
  colorNeutral8: string
  colorNeutral9: string
  colorNeutral10: string
  colorNeutral11: string
  colorWhite: string
  colorBlack: string
  colorGrey0: string
  colorGrey1: string
  colorGrey2: string
  colorGrey3: string
  colorGrey4: string
  colorGrey5: string
  colorGrey6: string
  colorGrey7: string
  colorGrey8: string
  colorGrey9: string
  colorGrey10: string
  colorGrey11: string
  colorOther1: string
  colorBg1: string
  colorBg2: string
  colorBg3: string
  colorFormComponentBg: string
  colorContentBg: string
  colorBodyBg: string
  bodyFill: string
  disabledBg: string
  disabledBorder: string
  disabledColor: string
  disabledDangerBg: string
  disabledDangerColor: string
  disabledDangerBorder: string
  disabledFill: string
  disabledDangerFill: string
  disabledIconColor: string
  fontFamily: string
  fontFamilyCuteIcons: string
  textSize: string
  textSizeSm: string
  textSizeMd: string
  textSizeLg: string
  textSizeXl: string
  textColor: string
  textColorLight: string
  textColorLight2: string
  textColorFeature: string
  textWeight: string
  textTitleWeight: string
  textSizePrimary: string
  textSizeSmall: string
  textSizeMedium: string
  textSizeLarge: string
  textSizeXLarge: string
  textColorPrimary: string
  textColorLight1: string
  lineHeight: string
  borderColor: string
  borderColorHover: string
  borderColorLight: string
  borderColorDark: string
  borderRadius: string
  borderRadiusMedium: string
  borderColorPrimary: string
  borderColorLight1: string
  borderColorDark1: string
  commonSpace: string
  commonSpace2x: string
  commonSpace3x: string
  commonSpace4x: string
  commonSpace5x: string
  commonSpace6x: string
  commonSpace7x: string
  commonSpace8x: string
  commonSpace9x: string
  commonSpace10x: string
  commonSpace6: string
  commonSpace10: string
  padding: string
  padding2x: string
  padding3x: string
  padding4x: string
  padding5x: string
  padding6x: string
  padding7x: string
  padding8x: string
  padding9x: string
  padding10x: string
  padding6: string
  padding10: string
  margin: string
  margin2x: string
  margin3x: string
  margin4x: string
  margin5x: string
  margin6x: string
  margin7x: string
  margin8x: string
  margin9x: string
  margin10x: string
  margin6: string
  margin10: string
  paddingPrimary: string
  paddingMedium: string
  paddingSmall: string
  paddingTiny: string
  marginLarge: string
  marginMedium: string
  marginSmall: string
  marginTiny: string
  marginPrimary: string
  shadow1: string
  shadow2: string
  shadow3: string
  shadowFormItem: string
  shadowInput: string
  shadowCard: string
  shadowDialog: string
  shadowTableCard: string
  tagMaster: string
  tagMasterBorder: string
  tagInfo: string
  tagInfoBorder: string
  tagSuccess: string
  tagSuccessBorder: string
  tagWarning: string
  tagWarningBorder: string
  tagDanger: string
  tagDangerBorder: string
  tagFatal: string
  tagFatalBorder: string
  tagWeak: string
  tagWeakBorder: string
  tagCt: string
  tagCtBorder: string
  colorTagMaster1: string
  colorTagMaster2: string
  colorTagInfo1: string
  colorTagInfo2: string
  colorTagSuccess1: string
  colorTagSuccess2: string
  colorTagWarning1: string
  colorTagWarning2: string
  colorTagDanger1: string
  colorTagDanger2: string
  buttonDefaultTextColor: string
  buttonDefaultTextColorDisabled: string
  buttonDefaultColorBg: string
  buttonDefaultColorBgDisabled: string
  buttonDefaultColorBorder: string
  buttonDefaultColorBorderDisabled: string
  buttonIconColor: string
  buttonMargin: string
  buttonPaddingMini: string
  buttonPaddingSmall: string
  buttonPaddingMedium: string
  buttonPaddingLarge: string
  buttonGroupBorder: string
  formItemLabelLineHeight: string
  formItemErrorPaddingTop: string
  formItemMarginBottom: string
  inputBg: string
  inputDisabledBg: string
  inputHoverBorder: string
  inputActiveBorder: string
  inputXsHeight: string
  inputSmHeight: string
  inputMdHeight: string
  inputLgHeight: string
  inputHeight: string
  inputPrefixPadding: string
  inputSuffixPadding: string
  inputFill: string
  selectBorderColorHover: string
  selectDisabledBorder: string
  checkboxBg: string
  checkboxBorder: string
  checkboxButton: string
  checkboxButtonHover: string
  tableHeaderBg: string
  tableCellBg: string
  tableCellPaddingXs: string
  tableCellPaddingSm: string
  tableCellPaddingMd: string
  tableCellPaddingLg: string
  tableCellSelectionLineHeight: string
  tableBorderColor: string
  tableSortCaretBg: string
  tableFixedBoxShadow: string
  tableRowHoverBackgroundColor: string
  tableFilterItemHeight: string
  tableHeaderFill: string
  tableCellFill: string
  tableSortCaretFill: string
  paginationBg: string
  paginationFill: string
  paginationFontSize: string
  paginationFontSizeSm: string
  paginationHeight: string
  paginationHeightSm: string
  paginationInputWidth: string
  paginationButtonWidth: string
  paginationButtonWidthSm: string
  paginationButtonMargin: string
  paginationButtonMarginSm: string
  paginationButtonColor: string
  paginationHoverColor: string
  paginationHoverBg: string
  paginationActiveColor: string
  paginationActiveBg: string
  paginationActiveBgDisabled: string
  transferHeaderHeight: string
  transferHeaderBg: string
  transferButtonHegiht: string
  transferButtonWidth: string
  transferButtonRadius: string
  transferItemActiveBg: string
  transferItemHoverBg: string
  transferItemHeight: string
  transferFilterHeight: string
  transferFootertBg: string
  transferFooterHeight: string
  progressTextHeightLg: string
  progressTextHeightSm: string
  progressTextSizeLg: string
  progressTextSizeSm: string
  progressTextWeight: string
  tooltipBg: string
  tooltopTextColor: string
  tooltipBorderColor: string
  tooltipFill: string
  notificationBorderColor: string
  popoverMinWidth: string
  uploadBg: string
  uploadFill: string
  cardBg: string
  cardShadow: string
  cascaderTagBg: string
  cascaderTagBorder: string
  cascaderTagCloseColor: string
  cascaderTagCloseBg: string
  cascaderNodeHover: string
  cascaderPanelBg: string
  cascaderPanelShadow: string
  collapseBorderColor: string
  collapseContentBackgroundColor: string
  collapseHeaderBg: string
  collapseHeaderArrowColor: string
  collapseHeaderHeight: string
  collapseSeperateHeaderHeight: string
  collapseSeperateHeaderBg: string
  collapseItemHeaderHeight: string
  collapseHeaderFill: string
  datepickerShadow: string
  descriptionsLabelWidth: string
  descriptionsItemHeight: string
  descriptionsItemContentWidth: string
  descriptionsItemContentLineHeight: string
  descriptionsItemLabelMinWidth: string
  descriptionsFontColorLabel: string
  descriptionsFontColorLabelBordered: string
  dropdownItemPaddingTopBottom: string
  dropdownMinWidth: string
  dropdownIconLineHeight: string
  treeCheckboxSize: string
  treeNodeIconPadding: string
  treeCheckboxTransform: string
  treeCheckboxScale: string
  treeCheckboxTickTop: string
  treeHandlerMenu: string
  treeNodePopoverMargin: string
  treeButtonTooltipContentPadding: string
  treeLeafExpandIconPadding: string
  stepsIconHeightMd: string
  stepsIconHeightSm: string
  stepsTitleSizeMd: string
  stepsTitleSizeSm: string
  stepsIconInnerStatusSizeMd: string
  stepsIconInnerStatusSizeSm: string
  stepsIconInnerTextSizeMd: string
  stepsIconInnerTextSizeSm: string
  stepsLineSize: string
  dialogHeaderPadding: string
  dialogHeaderBorder: string
  dialogBodyPadding: string
  dialogFooterBg: string
  dialogFooterPadding: string
  dialogFooterMarginTop: string
  dialogFullscreenMargin: string
  messageboxPaddingBottom: string
  messageboxHeaderPadding: string
  messageboxHeaderPaddingBottom: string
  messageboxContentPadding: string
  messageboxBtnsPadding: string
  toastWidth: string
  toastHeight: string
  iconColor: string
  loadingPrimaryColor: string
  loadingPrimaryBorder: string
  loadingDefaultColor: string
  loadingDefaultBorder: string
  alertTextColor: string
  alertInfoBg: string
  alertSuccessBg: string
  alertWarningBg: string
  alertDangerBg: string
  alertWeakBg: string
  cuteSliderMarksHeight: string
  cuteSliderBarHeight: string
  cuteSliderInputWidth: string
  cuteSliderBtnBg: string
  cuteSliderBtnRadius: string
  cuteSliderBtnWidth: string
  cuteSliderBtnHeight: string
  cuteDistributionBarInputWidth: string
  cuteDistributionBarSliderWidth: string
  cuteDistributionBarSliderHeight: string
  cuteDistributionBarSliderItemWidth: string
  cuteDistributionBarSliderItemHeight: string
  cuteDistributionBarSliderButtonWidth: string
  cuteDistributionBarSliderButtonHeight: string
  headerHeight: string
  headerFill1: string
  headerFill2: string
  headerBorder: string
  headerTextColor: string
  headerSearchTextColor: string
  sidebarWidth: string
  sidebarFill: string
  sidebarSubFill: string
  sidebarSubHover: string
  cuteButtonGroupMargin: string
  cuteButtonGroupZindex: string
  cuteButtonGroupBorder: string
  cuteEditInputWidth: string
  cuteRemindInputWidth: string
  cuteSpecialRadioPadding: string
  cuteSpecialRadioSize: string
  cuteRemindSelectRight: string
  cuteSelectedInputWidth: string
  transitionTime: string
  zindexBadge: string
  zindexTableFixed: string
  zindexAffix: string
  zindexBackTop: string
  zindexPickerPanel: string
  zindexPopupClose: string
  zindexModal: string
  zindexModalMask: string
  zindexMessage: string
  zindexNotification: string
  zindexPopover: string
  zindexDropdown: string
  zindexPicker: string
  zindexPopoconfirm: string
  zindexTooltip: string
  zindexImage: string
  screenLg: string
  chartColor1: string
  chartColor2: string
  chartColor3: string
  chartColor4: string
  chartColor5: string
  chartColor6: string
  chartColor7: string
  chartColor8: string
  chartColor9: string
  chartColor10: string
  chartColor11: string
  chartColor12: string
  chartColorH1: string
  chartColorH2: string
  chartColorH3: string
  chartColorH4: string
  chartColorH5: string
  chartColorH6: string
  chartColorH7: string
  chartColorH8: string
  chartColorH9: string
  chartColorH10: string
  chartColorH11: string
  chartColorH12: string
  chartColorL1: string
  chartColorL2: string
  chartColorL3: string
  chartColorL4: string
  chartColorL5: string
  chartColorL6: string
  chartColorL7: string
  chartColorL8: string
  chartColorL9: string
  chartColorL10: string
  chartColorL11: string
  chartColorL12: string
  alertTextColor: string
  alertInfoBg: string
  alertSuccessBg: string
  alertWarningBg: string
  alertDangerBg: string
  alertWeakBg: string
  transferHeaderHeight: string
  transferHeaderBg: string
  transferButtonHegiht: string
  transferButtonWidth: string
  transferButtonRadius: string
  transferItemActiveBg: string
  transferItemHoverBg: string
  transferItemHeight: string
  transferFilterHeigh: string
  cuteSliderMarksHeight: string
  cuteSliderBarHeight: string
  cuteSliderInputWidth: string
  cuteSliderBtnBg: string
  cuteSliderBtnRadius: string
  cuteSliderBtnWidth: string
  cuteSliderBtnHeight: string
  collapseBorderColor: string
  collapseContentBackgroundColor: string
  collapseHeaderBg: string
  collapseHeaderArrowColor: string
  collapseHeaderHeight: string
  collapseSeperateHeaderHeight: string
  collapseSeperateHeaderBg: string
  stepsIconHeightMd: string
  stepsIconHeightSm: string
  stepsTitleSizeMd: string
  stepsTitleSizeSm: string
  stepsIconInnerStatusSizeMd: string
  stepsIconInnerStatusSizeSm: string
  stepsIconInnerTextSizeMd: string
  stepsIconInnerTextSizeSm: string
  stepsLineSize: string
  tabsMaster: string
  tabsSmHeight: string
  tabsMdHeight: string
  tabsLgHeight: string
  tabsButtonRadius: string
}

export const variablesRevised: IScssVariablesRevised
export default variablesRevised
